[package]
name = "sqlx_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1", features = ["full"] }
